# Generated by Django 3.2.6 on 2021-08-02 11:40

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='类别')),
                ('image', models.ImageField(help_text='此处使用图标icon', upload_to='static/images/categories/%Y/%m/%d')),
                ('slug', models.SlugField(editable=False, max_length=200, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '类别',
                'verbose_name_plural': '类别',
                'ordering': ['-updated_date'],
            },
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='场景')),
                ('image', models.ImageField(help_text='此处使用图标icon', upload_to='static/images/scenarios/%Y/%m/%d')),
                ('slug', models.SlugField(editable=False, max_length=200, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='lease.category', verbose_name='品类')),
            ],
            options={
                'verbose_name': '场景',
                'verbose_name_plural': '场景',
                'ordering': ['-updated_date'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='商品')),
                ('image', models.ImageField(help_text='图片大小建议为300px*300px', upload_to='static/images/products/%Y/%m/%d', verbose_name='图片')),
                ('rent_price_not_null', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='月租赁价格')),
                ('rent_price_second', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True, verbose_name='月租赁价格（备选一）')),
                ('rent_price_third', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True, verbose_name='月租赁价格（备选二）')),
                ('deposit', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True, verbose_name='押金')),
                ('slug', models.SlugField(editable=False, max_length=200, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('detail', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True, verbose_name='细节')),
                ('parameter', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True, verbose_name='参数')),
                ('package', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True, verbose_name='包装')),
                ('guarantee', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True, verbose_name='保险')),
                ('purchase_consultation', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True, verbose_name='咨询')),
                ('on_sale', models.BooleanField(default=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='lease.scenario', verbose_name='场景')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'ordering': ['-updated_date'],
            },
        ),
    ]
