# Generated by Django 3.2.6 on 2021-08-04 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_auto_20210804_2317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['-created'], 'verbose_name': '城市', 'verbose_name_plural': '城市'},
        ),
        migrations.AlterModelOptions(
            name='county',
            options={'ordering': ['-created'], 'verbose_name': '县区', 'verbose_name_plural': '县区'},
        ),
        migrations.AlterModelOptions(
            name='province',
            options={'ordering': ['-created'], 'verbose_name': '省/州', 'verbose_name_plural': '省/州'},
        ),
        migrations.AlterField(
            model_name='city',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='address.province', verbose_name='城市'),
        ),
        migrations.AlterField(
            model_name='county',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counties', to='address.city', verbose_name='县区'),
        ),
        migrations.AlterField(
            model_name='province',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provinces', to='address.country', verbose_name='省/州'),
        ),
    ]
