# Generated by Django 3.2.6 on 2021-08-04 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('lease', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_amount', models.PositiveIntegerField(verbose_name='商品数量')),
                ('start_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('FP', '待购'), ('HB', '已购'), ('DE', '删除')], default='FP', max_length=10, verbose_name='状态')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer', verbose_name='顾客')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lease.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '购物车',
                'verbose_name_plural': '购物车',
                'ordering': ['-created'],
            },
        ),
    ]
