# Generated by Django 3.2.6 on 2021-08-04 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lease', '0001_initial'),
        ('customer', '0001_initial'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='customer.customer', verbose_name='顾客'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='lease.product', verbose_name='商品'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='start_date',
            field=models.DateField(),
        ),
    ]
