# Generated by Django 3.2.6 on 2021-08-04 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('cart', '0002_auto_20210804_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c', to='customer.customer', verbose_name='顾客'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='start_date',
            field=models.DateField(verbose_name='到货日期'),
        ),
    ]
